/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundationsTokenRouteImport } from './routes/foundations.$token'
import { Route as ComponentsTreeMenuRouteImport } from './routes/components.tree-menu'
import { Route as ComponentsTooltipRouteImport } from './routes/components.tooltip'
import { Route as ComponentsTableRouteImport } from './routes/components.table'
import { Route as ComponentsTabbedLayoutRouteImport } from './routes/components.tabbed-layout'
import { Route as ComponentsSwitchRouteImport } from './routes/components.switch'
import { Route as ComponentsSnackbarRouteImport } from './routes/components.snackbar'
import { Route as ComponentsRadioInputRouteImport } from './routes/components.radio-input'
import { Route as ComponentsMenuRouteImport } from './routes/components.menu'
import { Route as ComponentsFilterRouteImport } from './routes/components.filter'
import { Route as ComponentsFieldRouteImport } from './routes/components.field'
import { Route as ComponentsDropzoneRouteImport } from './routes/components.dropzone'
import { Route as ComponentsDialogRouteImport } from './routes/components.dialog'
import { Route as ComponentsDatepickerRouteImport } from './routes/components.datepicker'
import { Route as ComponentsChipRouteImport } from './routes/components.chip'
import { Route as ComponentsCheckboxRouteImport } from './routes/components.checkbox'
import { Route as ComponentsCardRouteImport } from './routes/components.card'
import { Route as ComponentsButtonRouteImport } from './routes/components.button'
import { Route as ComponentsAssetBarRouteImport } from './routes/components.asset-bar'
import { Route as ComponentsAppBarRouteImport } from './routes/components.app-bar'
import { Route as ComponentsAlertBarRouteImport } from './routes/components.alert-bar'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'
import { Route as ApiSbSplatRouteImport } from './routes/api/sb.$'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsTokenRoute = FoundationsTokenRouteImport.update({
  id: '/foundations/$token',
  path: '/foundations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTreeMenuRoute = ComponentsTreeMenuRouteImport.update({
  id: '/components/tree-menu',
  path: '/components/tree-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTableRoute = ComponentsTableRouteImport.update({
  id: '/components/table',
  path: '/components/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabbedLayoutRoute = ComponentsTabbedLayoutRouteImport.update({
  id: '/components/tabbed-layout',
  path: '/components/tabbed-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSnackbarRoute = ComponentsSnackbarRouteImport.update({
  id: '/components/snackbar',
  path: '/components/snackbar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioInputRoute = ComponentsRadioInputRouteImport.update({
  id: '/components/radio-input',
  path: '/components/radio-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsMenuRoute = ComponentsMenuRouteImport.update({
  id: '/components/menu',
  path: '/components/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFilterRoute = ComponentsFilterRouteImport.update({
  id: '/components/filter',
  path: '/components/filter',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFieldRoute = ComponentsFieldRouteImport.update({
  id: '/components/field',
  path: '/components/field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDropzoneRoute = ComponentsDropzoneRouteImport.update({
  id: '/components/dropzone',
  path: '/components/dropzone',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/components/dialog',
  path: '/components/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatepickerRoute = ComponentsDatepickerRouteImport.update({
  id: '/components/datepicker',
  path: '/components/datepicker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChipRoute = ComponentsChipRouteImport.update({
  id: '/components/chip',
  path: '/components/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAssetBarRoute = ComponentsAssetBarRouteImport.update({
  id: '/components/asset-bar',
  path: '/components/asset-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAppBarRoute = ComponentsAppBarRouteImport.update({
  id: '/components/app-bar',
  path: '/components/app-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertBarRoute = ComponentsAlertBarRouteImport.update({
  id: '/components/alert-bar',
  path: '/components/alert-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSbSplatRoute = ApiSbSplatRouteImport.update({
  id: '/api/sb/$',
  path: '/api/sb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/alert-bar': typeof ComponentsAlertBarRoute
  '/components/app-bar': typeof ComponentsAppBarRoute
  '/components/asset-bar': typeof ComponentsAssetBarRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/datepicker': typeof ComponentsDatepickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropzone': typeof ComponentsDropzoneRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/filter': typeof ComponentsFilterRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/radio-input': typeof ComponentsRadioInputRoute
  '/components/snackbar': typeof ComponentsSnackbarRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabbed-layout': typeof ComponentsTabbedLayoutRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/tree-menu': typeof ComponentsTreeMenuRoute
  '/foundations/$token': typeof FoundationsTokenRoute
  '/api/sb/$': typeof ApiSbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/alert-bar': typeof ComponentsAlertBarRoute
  '/components/app-bar': typeof ComponentsAppBarRoute
  '/components/asset-bar': typeof ComponentsAssetBarRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/datepicker': typeof ComponentsDatepickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropzone': typeof ComponentsDropzoneRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/filter': typeof ComponentsFilterRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/radio-input': typeof ComponentsRadioInputRoute
  '/components/snackbar': typeof ComponentsSnackbarRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabbed-layout': typeof ComponentsTabbedLayoutRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/tree-menu': typeof ComponentsTreeMenuRoute
  '/foundations/$token': typeof FoundationsTokenRoute
  '/api/sb/$': typeof ApiSbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/alert-bar': typeof ComponentsAlertBarRoute
  '/components/app-bar': typeof ComponentsAppBarRoute
  '/components/asset-bar': typeof ComponentsAssetBarRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/datepicker': typeof ComponentsDatepickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropzone': typeof ComponentsDropzoneRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/filter': typeof ComponentsFilterRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/radio-input': typeof ComponentsRadioInputRoute
  '/components/snackbar': typeof ComponentsSnackbarRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabbed-layout': typeof ComponentsTabbedLayoutRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/tree-menu': typeof ComponentsTreeMenuRoute
  '/foundations/$token': typeof FoundationsTokenRoute
  '/api/sb/$': typeof ApiSbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/templates'
    | '/components/$slug'
    | '/components/alert-bar'
    | '/components/app-bar'
    | '/components/asset-bar'
    | '/components/button'
    | '/components/card'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/datepicker'
    | '/components/dialog'
    | '/components/dropzone'
    | '/components/field'
    | '/components/filter'
    | '/components/menu'
    | '/components/radio-input'
    | '/components/snackbar'
    | '/components/switch'
    | '/components/tabbed-layout'
    | '/components/table'
    | '/components/tooltip'
    | '/components/tree-menu'
    | '/foundations/$token'
    | '/api/sb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/templates'
    | '/components/$slug'
    | '/components/alert-bar'
    | '/components/app-bar'
    | '/components/asset-bar'
    | '/components/button'
    | '/components/card'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/datepicker'
    | '/components/dialog'
    | '/components/dropzone'
    | '/components/field'
    | '/components/filter'
    | '/components/menu'
    | '/components/radio-input'
    | '/components/snackbar'
    | '/components/switch'
    | '/components/tabbed-layout'
    | '/components/table'
    | '/components/tooltip'
    | '/components/tree-menu'
    | '/foundations/$token'
    | '/api/sb/$'
  id:
    | '__root__'
    | '/'
    | '/templates'
    | '/components/$slug'
    | '/components/alert-bar'
    | '/components/app-bar'
    | '/components/asset-bar'
    | '/components/button'
    | '/components/card'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/datepicker'
    | '/components/dialog'
    | '/components/dropzone'
    | '/components/field'
    | '/components/filter'
    | '/components/menu'
    | '/components/radio-input'
    | '/components/snackbar'
    | '/components/switch'
    | '/components/tabbed-layout'
    | '/components/table'
    | '/components/tooltip'
    | '/components/tree-menu'
    | '/foundations/$token'
    | '/api/sb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesRoute: typeof TemplatesRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsAlertBarRoute: typeof ComponentsAlertBarRoute
  ComponentsAppBarRoute: typeof ComponentsAppBarRoute
  ComponentsAssetBarRoute: typeof ComponentsAssetBarRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsChipRoute: typeof ComponentsChipRoute
  ComponentsDatepickerRoute: typeof ComponentsDatepickerRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsDropzoneRoute: typeof ComponentsDropzoneRoute
  ComponentsFieldRoute: typeof ComponentsFieldRoute
  ComponentsFilterRoute: typeof ComponentsFilterRoute
  ComponentsMenuRoute: typeof ComponentsMenuRoute
  ComponentsRadioInputRoute: typeof ComponentsRadioInputRoute
  ComponentsSnackbarRoute: typeof ComponentsSnackbarRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTabbedLayoutRoute: typeof ComponentsTabbedLayoutRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsTreeMenuRoute: typeof ComponentsTreeMenuRoute
  FoundationsTokenRoute: typeof FoundationsTokenRoute
  ApiSbSplatRoute: typeof ApiSbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/$token': {
      id: '/foundations/$token'
      path: '/foundations/$token'
      fullPath: '/foundations/$token'
      preLoaderRoute: typeof FoundationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tree-menu': {
      id: '/components/tree-menu'
      path: '/components/tree-menu'
      fullPath: '/components/tree-menu'
      preLoaderRoute: typeof ComponentsTreeMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/table': {
      id: '/components/table'
      path: '/components/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabbed-layout': {
      id: '/components/tabbed-layout'
      path: '/components/tabbed-layout'
      fullPath: '/components/tabbed-layout'
      preLoaderRoute: typeof ComponentsTabbedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/snackbar': {
      id: '/components/snackbar'
      path: '/components/snackbar'
      fullPath: '/components/snackbar'
      preLoaderRoute: typeof ComponentsSnackbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio-input': {
      id: '/components/radio-input'
      path: '/components/radio-input'
      fullPath: '/components/radio-input'
      preLoaderRoute: typeof ComponentsRadioInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/components/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/filter': {
      id: '/components/filter'
      path: '/components/filter'
      fullPath: '/components/filter'
      preLoaderRoute: typeof ComponentsFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/field': {
      id: '/components/field'
      path: '/components/field'
      fullPath: '/components/field'
      preLoaderRoute: typeof ComponentsFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dropzone': {
      id: '/components/dropzone'
      path: '/components/dropzone'
      fullPath: '/components/dropzone'
      preLoaderRoute: typeof ComponentsDropzoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/components/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/datepicker': {
      id: '/components/datepicker'
      path: '/components/datepicker'
      fullPath: '/components/datepicker'
      preLoaderRoute: typeof ComponentsDatepickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chip': {
      id: '/components/chip'
      path: '/components/chip'
      fullPath: '/components/chip'
      preLoaderRoute: typeof ComponentsChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card': {
      id: '/components/card'
      path: '/components/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/asset-bar': {
      id: '/components/asset-bar'
      path: '/components/asset-bar'
      fullPath: '/components/asset-bar'
      preLoaderRoute: typeof ComponentsAssetBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/app-bar': {
      id: '/components/app-bar'
      path: '/components/app-bar'
      fullPath: '/components/app-bar'
      preLoaderRoute: typeof ComponentsAppBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert-bar': {
      id: '/components/alert-bar'
      path: '/components/alert-bar'
      fullPath: '/components/alert-bar'
      preLoaderRoute: typeof ComponentsAlertBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sb/$': {
      id: '/api/sb/$'
      path: '/api/sb/$'
      fullPath: '/api/sb/$'
      preLoaderRoute: typeof ApiSbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesRoute: TemplatesRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsAlertBarRoute: ComponentsAlertBarRoute,
  ComponentsAppBarRoute: ComponentsAppBarRoute,
  ComponentsAssetBarRoute: ComponentsAssetBarRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsChipRoute: ComponentsChipRoute,
  ComponentsDatepickerRoute: ComponentsDatepickerRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsDropzoneRoute: ComponentsDropzoneRoute,
  ComponentsFieldRoute: ComponentsFieldRoute,
  ComponentsFilterRoute: ComponentsFilterRoute,
  ComponentsMenuRoute: ComponentsMenuRoute,
  ComponentsRadioInputRoute: ComponentsRadioInputRoute,
  ComponentsSnackbarRoute: ComponentsSnackbarRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTabbedLayoutRoute: ComponentsTabbedLayoutRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsTreeMenuRoute: ComponentsTreeMenuRoute,
  FoundationsTokenRoute: FoundationsTokenRoute,
  ApiSbSplatRoute: ApiSbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
